<?php
	// French Translation
	$L = array(
		'site_title' => 'Site web en français',
		'read_more' => 'Lire plus',
		'next' => 'Suivant',
		'prev' => 'Précédent',
		'fr' => 'français',
		'en' => 'anglais',
		'Latest Blog Entries' => 'Les derniers billets du blog',
		'not_translated_short' => '(en anglais)',
		'alt_lang' => 'en',
		'by' => 'par',

		//Reserved strings; Polyglot will use these to format dates and numbers using {exp:polyglot:num} and {exp:polyglot:date}
		'January' => 'janvier',
		'February' => 'février',
		'March' => 'mars',
		'April' => 'avril',
		'May' => 'mai',
		'June' => 'juin',
		'July' => 'juillet',
		'August' => 'août',
		'September' => 'septembre',
		'October' => 'octobre',
		'November' => 'novembre',
		'December' => 'décembre',
		'Jan' => 'janv',
		'Feb' => 'fév',
		'Mar' => 'mar',
		'Apr' => 'avr',
		'Jun' => 'juin',
		'Jul' => 'juil',
		'Aug' => 'août',
		'Sep' => 'sept',
		'Oct' => 'oct',
		'Nov' => 'nov',
		'Dec' => 'déc',
		'Monday' => 'lundi',
		'Tuesday' => 'mardi',
		'Wednesday' => 'mercredi',
		'Thursday' => 'jeudi',
		'Friday' => 'vendredi',
		'Saturday' => 'samedi',
		'Sunday' => 'dimanche',
		'Mon' => 'lun',
		'Tue' => 'mar',
		'Wed' => 'mer',
		'Thu' => 'jeu',
		'Fri' => 'ven',
		'Sat' => 'sam',
		'Sun' => 'dim',
		'long_date_format' => 'l j F Y',
		'dec_point' => ',',
		'thousands_sep' => ' ',
		'currency_symbol' => '&euro;',
		'currency_pos' => 'after',
	);

	$S = array(
		'blog' => 'blogue',
	);
?>